name = "auth-rpc"
main = "src/index.ts"
compatibility_date = "2023-01-21"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
    { binding = "USERS", id = "a92b10144ef74ec79c2a8f4d89b91818", preview_id = "f194555617424296ad7f3eea42556d33" }
]